config/routes.rb
Rails.application.routes.draw do
  resources :pools
  devise_for :users
  resources :forecasts
  resources :games
  resources :teams
  resources :admin
  resources :profile
  get '/get_games', to: 'admin#get_new_week', as: 'get_games'
  get '/count_points', to: 'admin#count_week_points', as: 'count_points'

  root 'profile#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord

  require 'json'
  require 'open-uri'

  def can_edit?
    if self.scheduled_at > DateTime.now
      puts "Mayor QUE"
      return true
    else
      found = false
      puts "WHAAAT"
      data = JSON.load(open("http://www.nfl.com/liveupdate/scores/scores.json"))

      data.each do |a, b|
        if a.to_i == self.id
          found = true
          if b['qtr'] != nil and b['qtr'] != 'Pregame'
            self.editable = false
            self.save
            return false
          else
            return true
          end
        end
      end
      if !found
        self.editable = false
        self.save
        return false
      end
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all.order(scheduled_at: :desc)
    @teams = Team.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:home_team, :away_team, :scheduled_at, :home_team_score, :away_team_score, :week, :season)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :home_team %>
    <%= form.number_field :home_team %>
  </div>

  <div class="field">
    <%= form.label :away_team %>
    <%= form.number_field :away_team %>
  </div>

  <div class="field">
    <%= form.label :scheduled_at %>
    <%= form.datetime_select :scheduled_at %>
  </div>

  <div class="field">
    <%= form.label :home_team_score %>
    <%= form.number_field :home_team_score %>
  </div>

  <div class="field">
    <%= form.label :away_team_score %>
    <%= form.number_field :away_team_score %>
  </div>

  <div class="field">
    <%= form.label :week %>
    <%= form.number_field :week %>
  </div>

  <div class="field">
    <%= form.label :season %>
    <%= form.number_field :season %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="row">
  <div class="col-md-12">
    <p id="notice"><%= notice %></p>

    <h1>Juegos</h1>
    <br>
    <br>
    <table class="table text-center">
      <thead>
        <tr>
          <th class="text-center">Local</th>
          <th class="text-center">Visitante</th>
          <th class="text-center">Día de Juego</th>
          <th class="text-center">Semana</th>
          <th class="text-center">Temporada</th>
        </tr>
      </thead>

      <tbody>
        <% @games.each do |game| %>
        <tr>
          <td><%= @teams.where(id: game.home_team).first.name %><br><b><%= game.home_team_score %></b></td>
          <td><%= @teams.where(id: game.away_team).first.name %><br><b><%= game.away_team_score %></b></td>
          <td><%= game.scheduled_at.strftime("%B %d, %Y, %A") %></td>
          <td><%= game.week %></td>
          <td><%= game.season %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <br>

  </div>
</div>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Home team:</strong>
  <%= @game.home_team %>
</p>

<p>
  <strong>Away team:</strong>
  <%= @game.away_team %>
</p>

<p>
  <strong>Scheduled at:</strong>
  <%= @game.scheduled_at %>
</p>

<p>
  <strong>Home team score:</strong>
  <%= @game.home_team_score %>
</p>

<p>
  <strong>Away team score:</strong>
  <%= @game.away_team_score %>
</p>

<p>
  <strong>Week:</strong>
  <%= @game.week %>
</p>

<p>
  <strong>Season:</strong>
  <%= @game.season %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>