config/routes.rb
Rails.application.routes.draw do
  resources :pools
  devise_for :users
  resources :forecasts
  resources :games
  resources :teams
  resources :admin
  resources :profile
  get '/get_games', to: 'admin#get_new_week', as: 'get_games'
  get '/count_points', to: 'admin#count_week_points', as: 'count_points'

  root 'profile#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/forecast.rb
class Forecast < ApplicationRecord
  belongs_to :game
  belongs_to :pool
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  before_action :set_forecast, only: [:show, :edit, :update, :destroy]

  # GET /forecasts
  # GET /forecasts.json
  def index
    @forecasts = Forecast.all
  end

  # GET /forecasts/1
  # GET /forecasts/1.json
  def show
  end

  # GET /forecasts/new
  def new
    @forecast = Forecast.new
  end

  # GET /forecasts/1/edit
  def edit
  end

  # POST /forecasts
  # POST /forecasts.json
  def create
    @forecast = Forecast.new(forecast_params)

    respond_to do |format|
      if @forecast.save
        format.html { redirect_to @forecast, notice: 'Forecast was successfully created.' }
        format.json { render :show, status: :created, location: @forecast }
      else
        format.html { render :new }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forecasts/1
  # PATCH/PUT /forecasts/1.json
  def update
    if @forecast.pool.user == current_user
      @teams = Team.all
      if @forecast.game.can_edit?
        respond_to do |format|
          if @forecast.update(selection: params[:selection])
            format.html { redirect_to @forecast.pool, notice: 'Forecast was successfully updated.' }
            format.json { render :show, status: :ok, location: @forecast }
            format.js
          else
            format.html { render :edit }
            format.json { render json: @forecast.errors, status: :unprocessable_entity }
          end
        end
      else
        respond_to do |format|
          format.js
        end
      end
    end
  end

  # DELETE /forecasts/1
  # DELETE /forecasts/1.json
  def destroy
    @forecast.destroy
    respond_to do |format|
      format.html { redirect_to forecasts_url, notice: 'Forecast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forecast
      @forecast = Forecast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forecast_params
      params.require(:forecast).permit(:game_id, :selection)
    end
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/views/forecasts/_form.html.erb
<%= form_with(model: forecast, local: true) do |form| %>
  <% if forecast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forecast.errors.count, "error") %> prohibited this forecast from being saved:</h2>

      <ul>
      <% forecast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game_id %>
    <%= form.text_field :game_id %>
  </div>

  <div class="field">
    <%= form.label :selection %>
    <%= form.text_field :selection %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/forecasts/_show.html.erb
<% if @forecast.game.editable %>
  <% if @forecast.selection == "away" %>
  <td><%= button_to @teams.find(@forecast.game.away_team).name, forecast, method: :put, params: {selection: "away"}, class: "remote-update btn btn-sm btn-primary" , remote: :true , style:"white-space:normal"%></td>
  <td><%= button_to "Empate", forecast, method: :put, params: {selection: "draw"}, class: "remote-update btn btn-sm btn-default" , remote: :true , style:"white-space:normal"%></td>
  <td><%= button_to @teams.find(@forecast.game.home_team).name, forecast, method: :put, params: {selection: "home"}, class: "remote-update btn btn-sm btn-default" , remote: :true , style:"white-space:normal"%></td>
  <% elsif @forecast.selection == "draw" %>
  <td><%= button_to @teams.find(@forecast.game.away_team).name, forecast, method: :put, params: {selection: "away"}, class: "remote-update btn btn-sm btn-default" , remote: :true , style:"white-space:normal"%></td>
  <td><%= button_to "Empate", forecast, method: :put, params: {selection: "draw"}, class: "remote-update btn btn-sm btn-primary" , remote: :true , style:"white-space:normal"%></td>
  <td><%= button_to @teams.find(@forecast.game.home_team).name, forecast, method: :put, params: {selection: "home"}, class: "remote-update btn btn-sm btn-default" , remote: :true , style:"white-space:normal"%></td>
  <% elsif @forecast.selection == "home" %>
  <td><%= button_to @teams.find(@forecast.game.away_team).name, forecast, method: :put, params: {selection: "away"}, class: "remote-update btn btn-sm btn-default" , remote: :true , style:"white-space:normal"%></td>
  <td><%= button_to "Empate", forecast, method: :put, params: {selection: "draw"}, class: "remote-update btn btn-sm btn-default" , remote: :true , style:"white-space:normal"%></td>
  <td><%= button_to @teams.find(@forecast.game.home_team).name, forecast, method: :put, params: {selection: "home"}, class: "remote-update btn btn-sm btn-primary" , remote: :true , style:"white-space:normal"%></td>
  <% else %>
  <td><%= button_to @teams.find(@forecast.game.away_team).name, forecast, method: :put, params: {selection: "away"}, class: "remote-update btn btn-sm btn-default" , remote: :true , style:"white-space:normal"%></td>
  <td><%= button_to "Empate", forecast, method: :put, params: {selection: "draw"}, class: "remote-update btn btn-sm btn-default" , remote: :true , style:"white-space:normal"%></td>
  <td><%= button_to @teams.find(@forecast.game.home_team).name, forecast, method: :put, params: {selection: "home"}, class: "remote-update btn btn-sm btn-default" , remote: :true , style:"white-space:normal"%></td>
  <% end %>
<% else %>
  <% if @forecast.selection == "away" %>
  <td><%= button_to @teams.find(@forecast.game.away_team).name, forecast, method: :put, params: {selection: "away"}, class: "remote-update btn btn-sm btn-primary" , remote: :true , disabled:true , style:"white-space:normal"%></td>
  <td><%= button_to "Empate", forecast, method: :put, params: {selection: "draw"}, class: "remote-update btn btn-sm btn-default" , remote: :true , disabled:true , style:"white-space:normal"%></td>
  <td><%= button_to @teams.find(@forecast.game.home_team).name, forecast, method: :put, params: {selection: "home"}, class: "remote-update btn btn-sm btn-default" , remote: :true , disabled:true , style:"white-space:normal"%></td>
  <% elsif @forecast.selection == "draw" %>
  <td><%= button_to @teams.find(@forecast.game.away_team).name, forecast, method: :put, params: {selection: "away"}, class: "remote-update btn btn-sm btn-default" , remote: :true , disabled:true , style:"white-space:normal"%></td>
  <td><%= button_to "Empate", forecast, method: :put, params: {selection: "draw"}, class: "remote-update btn btn-sm btn-primary" , remote: :true, disabled:true  , style:"white-space:normal"%></td>
  <td><%= button_to @teams.find(@forecast.game.home_team).name, forecast, method: :put, params: {selection: "home"}, class: "remote-update btn btn-sm btn-default" , remote: :true , disabled:true , style:"white-space:normal"%></td>
  <% elsif @forecast.selection == "home" %>
  <td><%= button_to @teams.find(@forecast.game.away_team).name, forecast, method: :put, params: {selection: "away"}, class: "remote-update btn btn-sm btn-default" , remote: :true , disabled:true , style:"white-space:normal"%></td>
  <td><%= button_to "Empate", forecast, method: :put, params: {selection: "draw"}, class: "remote-update btn btn-sm btn-default" , remote: :true , disabled:true , style:"white-space:normal"%></td>
  <td><%= button_to @teams.find(@forecast.game.home_team).name, forecast, method: :put, params: {selection: "home"}, class: "remote-update btn btn-sm btn-primary" , remote: :true , disabled:true , style:"white-space:normal"%></td>
  <% else %>
  <td><%= button_to @teams.find(@forecast.game.away_team).name, forecast, method: :put, params: {selection: "away"}, class: "remote-update btn btn-sm btn-default" , remote: :true , disabled:true , style:"white-space:normal"%></td>
  <td><%= button_to "Empate", forecast, method: :put, params: {selection: "draw"}, class: "remote-update btn btn-sm btn-default" , remote: :true , disabled:true , style:"white-space:normal"%></td>
  <td><%= button_to @teams.find(@forecast.game.home_team).name, forecast, method: :put, params: {selection: "home"}, class: "remote-update btn btn-sm btn-default" , remote: :true , disabled:true , style:"white-space:normal"%></td>
  <% end %>
<% end %>

app/views/forecasts/edit.html.erb
<h1>Editing Forecast</h1>

<%= render 'form', forecast: @forecast %>

<%= link_to 'Show', @forecast %> |
<%= link_to 'Back', forecasts_path %>

app/views/forecasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forecasts</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Selection</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forecasts.each do |forecast| %>
      <tr>
        <td><%= forecast.game %></td>
        <td><%= forecast.selection %></td>
        <td><%= link_to 'Show', forecast %></td>
        <td><%= link_to 'Edit', edit_forecast_path(forecast) %></td>
        <td><%= link_to 'Destroy', forecast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forecast', new_forecast_path %>

app/views/forecasts/new.html.erb
<h1>New Forecast</h1>

<%= render 'form', forecast: @forecast %>

<%= link_to 'Back', forecasts_path %>

app/views/forecasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @forecast.game %>
</p>

<p>
  <strong>Selection:</strong>
  <%= @forecast.selection %>
</p>

<%= link_to 'Edit', edit_forecast_path(@forecast) %> |
<%= link_to 'Back', forecasts_path %>

app/views/forecasts/update.js.erb
console.log("Editando Pronóstico");
//alert("Hello");
$('#forecast-<%= @forecast.id %>').html('<%= j render "show", forecast: @forecast %>');

/*$('.remote-update').bind('ajax:success', function() {
});
*/