config/routes.rb
Rails.application.routes.draw do
  resources :pools
  devise_for :users
  resources :forecasts
  resources :games
  resources :teams
  resources :admin
  resources :profile
  get '/get_games', to: 'admin#get_new_week', as: 'get_games'
  get '/count_points', to: 'admin#count_week_points', as: 'count_points'

  root 'profile#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuinielaNfl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Quiniela NFL Monroy', root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Juegos', games_path %></li>
            <li><%= link_to 'Quinielas', pools_path %></li>
            <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Perfil', profile_index_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to('Cerrar Sesión', destroy_user_session_path, method: :delete) %></li>
              </ul>
            </li>
            <% else %>
            <li><%= link_to('Iniciar Sesión', new_user_session_path) %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>